config/routes.rb
Rails.application.routes.draw do
  get  'todos', to: 'todos#index'
  get 'todos/new'
  get 'todos/list'
  post 'todos', to: 'todos#create'
  get  'todos/:id', to: 'todos#show', as: 'todo'
  get 'todos/:id/edit', to: 'todos#edit', as: 'editando'
  patch 'todos/:id', to:'todos#update'
  delete 'todos/:id', to: 'todos#destroy'
  get 'todos/:id/complete', to: 'todos#complete', as:'complete_todo'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
  validates :description, presence: :true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  def index
    @todos = Todo.all
  end

  def new
    @todo = Todo.new
  end

  def create
    @todo = Todo.new(todo_params)
    @todo.save
    redirect_to todos_path
  end

  def show
    @todo = Todo.find(params[:id])
  end

  def edit
    @todo = Todo.find(params[:id])
  end

  def update
    @todo = Todo.find(params[:id])
    @todo.update(todo_params)
    redirect_to todos_path
  end

  def destroy
    @todo = Todo.find(params[:id])
    @todo.destroy
    redirect_to todos_path
  end

  def complete
    @todo = Todo.find(params[:id])
    @todo.update_attribute(:completed, true)
    redirect_to todos_path
  end
  
  def list
    @todos = Todo.all
  end

  private
  def todo_params
    params.require(:todo).permit(:description, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
        <li class="nav-item active">
            <%= link_to 'Index', todos_path, class:"nav-link" %>
          </li>
        <li class="nav-item">
            <%= link_to 'List', todos_list_path, class:"nav-link" %>
          </li>
        <li class="nav-item">
            <%= link_to 'Nuevo', todos_new_path, class:"nav-link" %>
          </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoApp</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  </head>
  <%= render 'layouts/nav' %>
  <body>
    <%= yield %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

app/views/todos/_form.html.erb
<div class="container">
  <%= form_with model: @todo, local: true do |f| %>
        <%= f.text_field :description %>
        <%= f.submit "Enviar" %>
  <% end %>
  <%= link_to "nuevo ToDo", todos_new_path %>
</div>

app/views/todos/edit.html.erb
<%= render 'todos/form' %>

app/views/todos/index.html.erb
<div class="container">
  <h1>Bienvenido</h1>
  <%= link_to "Agrega una nueva tarea", todos_new_path %>
  <p> Estas son tus tareas </p>
  <% @todos.each do |todo| %>
    <h3> <%= todo.description %> </h3>
    <p> <%= todo.completed %> </p>
    <%= link_to "Show", todo, class: 'btn btn-primary' %>
    <%= link_to "Borrar", todo, method: :delete, class: 'btn btn-primary' %>
    <%= link_to "Completado", complete_todo_path(todo), class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/todos/list.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6">
      <h1>completo</h1>
      <% @todos.each do |v| %>
        <% if v.completed == true %>
        <p> <%= v.description %> </p>
        <% end %>
      <% end %>
    </div>
    <div class="col-md-6">
      <h1>incompleto</h1>
      <% @todos.each do |v| %>
        <% if v.completed != true %>
        <p> <%= v.description %> </p>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/todos/new.html.erb
<%= render 'todos/form' %>

app/views/todos/show.html.erb
<h1> <%= @todo.description %> </h1>
<p> <%= @todo.completed %> </p>
<%= link_to "Editar", editando_url %>
<%= link_to "Nuevo", todos_new_path %>